# Generated by Django 4.2.7 on 2025-08-14 07:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Virement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('initie', 'Initié'), ('rejete', 'Rejeté')], default='initie', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('beneficiaire_nom', models.CharField(max_length=200, verbose_name='Nom du bénéficiaire')),
                ('beneficiaire_prenom', models.CharField(max_length=200, verbose_name='Prénom du bénéficiaire')),
                ('beneficiaire_email', models.EmailField(max_length=254, verbose_name='Email du bénéficiaire')),
                ('beneficiaire_compte', models.CharField(max_length=50, verbose_name='Numéro de compte bénéficiaire')),
                ('numero_bic', models.CharField(max_length=11, verbose_name='Numéro BIC')),
                ('donneur_ordre_nom', models.CharField(max_length=200, verbose_name="Nom du donneur d'ordre")),
                ('donneur_ordre_prenom', models.CharField(max_length=200, verbose_name="Prénom du donneur d'ordre")),
                ('donneur_ordre_compte', models.CharField(max_length=50, verbose_name="Numéro de compte donneur d'ordre")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant du virement')),
                ('devise', models.CharField(choices=[('EUR', 'Euro (EUR)'), ('USD', 'Dollar américain (USD)'), ('CHF', 'Franc suisse (CHF)'), ('CAD', 'Dollar canadien (CAD)'), ('GBP', 'Livre sterling (GBP)'), ('PLN', 'Zloty polonais (PLN)'), ('RUB', 'Rouble russe (RUB)')], default='EUR', max_length=3)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('it', 'Italiano'), ('de', 'Deutsch'), ('pl', 'Polski'), ('ru', 'Русский')], default='fr', max_length=2)),
                ('banque_emettrice', models.CharField(choices=[('bnp_paribas', 'BNP Paribas'), ('credit_agricole', 'Crédit Agricole'), ('bnp_paribas_fortis', 'BNP Paribas Fortis'), ('credit_mutuel', 'Crédit Mutuel'), ('credit_suisse', 'Crédit Suisse'), ('credit_lyonnais', 'Crédit Lyonnais'), ('banque_populaire', 'Banque Populaire'), ('societe_generale', 'Société Générale'), ('intesa_sanpaolo', 'Intesa Sanpaolo'), ('deutsche_bank', 'Deutsche Bank')], max_length=50)),
                ('pdf_initiation', models.FileField(blank=True, null=True, upload_to='pdfs/initiations/')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Virement',
                'verbose_name_plural': 'Virements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RejetVirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_redirection', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de redirection')),
                ('motif_rejet', models.TextField(verbose_name='Motif du rejet')),
                ('date_rejet', models.DateTimeField(auto_now_add=True)),
                ('pdf_rejet', models.FileField(blank=True, null=True, upload_to='pdfs/rejets/')),
                ('virement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejet', to='virements.virement')),
            ],
            options={
                'verbose_name': 'Rejet de virement',
                'verbose_name_plural': 'Rejets de virements',
                'ordering': ['-date_rejet'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_compte', models.CharField(choices=[('standard', 'Standard (40 virements)'), ('premium', 'Premium (100 virements)')], default='standard', max_length=10)),
                ('quota_utilise', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
